---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.9

inputs:
  - name: dp-search-data-finder

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-search-data-finder/ci/scripts/build.sh
