// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-search-data-finder/clients"
	"sync"
)

var (
	lockZebedeeClientMockChecker           sync.RWMutex
	lockZebedeeClientMockGetPublishedIndex sync.RWMutex
)

// Ensure, that ZebedeeClientMock does implement clients.ZebedeeClient.
// If this is not the case, regenerate this file with moq.
var _ clients.ZebedeeClient = &ZebedeeClientMock{}

// ZebedeeClientMock is a mock implementation of clients.ZebedeeClient.
//
//     func TestSomethingThatUsesZebedeeClient(t *testing.T) {
//
//         // make and configure a mocked clients.ZebedeeClient
//         mockedZebedeeClient := &ZebedeeClientMock{
//             CheckerFunc: func(in1 context.Context, in2 *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             GetPublishedIndexFunc: func(ctx context.Context, publishedIndexRequestParams *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error) {
// 	               panic("mock out the GetPublishedIndex method")
//             },
//         }
//
//         // use mockedZebedeeClient in code that requires clients.ZebedeeClient
//         // and then make assertions.
//
//     }
type ZebedeeClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(in1 context.Context, in2 *healthcheck.CheckState) error

	// GetPublishedIndexFunc mocks the GetPublishedIndex method.
	GetPublishedIndexFunc func(ctx context.Context, publishedIndexRequestParams *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// In1 is the in1 argument value.
			In1 context.Context
			// In2 is the in2 argument value.
			In2 *healthcheck.CheckState
		}
		// GetPublishedIndex holds details about calls to the GetPublishedIndex method.
		GetPublishedIndex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublishedIndexRequestParams is the publishedIndexRequestParams argument value.
			PublishedIndexRequestParams *zebedee.PublishedIndexRequestParams
		}
	}
}

// Checker calls CheckerFunc.
func (mock *ZebedeeClientMock) Checker(in1 context.Context, in2 *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ZebedeeClientMock.CheckerFunc: method is nil but ZebedeeClient.Checker was just called")
	}
	callInfo := struct {
		In1 context.Context
		In2 *healthcheck.CheckState
	}{
		In1: in1,
		In2: in2,
	}
	lockZebedeeClientMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockZebedeeClientMockChecker.Unlock()
	return mock.CheckerFunc(in1, in2)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedZebedeeClient.CheckerCalls())
func (mock *ZebedeeClientMock) CheckerCalls() []struct {
	In1 context.Context
	In2 *healthcheck.CheckState
} {
	var calls []struct {
		In1 context.Context
		In2 *healthcheck.CheckState
	}
	lockZebedeeClientMockChecker.RLock()
	calls = mock.calls.Checker
	lockZebedeeClientMockChecker.RUnlock()
	return calls
}

// GetPublishedIndex calls GetPublishedIndexFunc.
func (mock *ZebedeeClientMock) GetPublishedIndex(ctx context.Context, publishedIndexRequestParams *zebedee.PublishedIndexRequestParams) (zebedee.PublishedIndex, error) {
	if mock.GetPublishedIndexFunc == nil {
		panic("ZebedeeClientMock.GetPublishedIndexFunc: method is nil but ZebedeeClient.GetPublishedIndex was just called")
	}
	callInfo := struct {
		Ctx                         context.Context
		PublishedIndexRequestParams *zebedee.PublishedIndexRequestParams
	}{
		Ctx:                         ctx,
		PublishedIndexRequestParams: publishedIndexRequestParams,
	}
	lockZebedeeClientMockGetPublishedIndex.Lock()
	mock.calls.GetPublishedIndex = append(mock.calls.GetPublishedIndex, callInfo)
	lockZebedeeClientMockGetPublishedIndex.Unlock()
	return mock.GetPublishedIndexFunc(ctx, publishedIndexRequestParams)
}

// GetPublishedIndexCalls gets all the calls that were made to GetPublishedIndex.
// Check the length with:
//     len(mockedZebedeeClient.GetPublishedIndexCalls())
func (mock *ZebedeeClientMock) GetPublishedIndexCalls() []struct {
	Ctx                         context.Context
	PublishedIndexRequestParams *zebedee.PublishedIndexRequestParams
} {
	var calls []struct {
		Ctx                         context.Context
		PublishedIndexRequestParams *zebedee.PublishedIndexRequestParams
	}
	lockZebedeeClientMockGetPublishedIndex.RLock()
	calls = mock.calls.GetPublishedIndex
	lockZebedeeClientMockGetPublishedIndex.RUnlock()
	return calls
}
